### ISSUE TITLE
Got Errors after updating Elvui to 12.85

### ISSUE THREAD

**Issue by uaeuaeuae** [Benik/BenikUI#12]
Hi, I got errors after updating Elvui 12.85 , after Disable BenikUI no errors ,pls update ,thank you

6x ...\ElvUI_BenikUI\modules\unitframes\elements\power.lua:48: attempt to index field 'textures' (a nil value)
[string "@ElvUI_BenikUI\modules\unitframes\elements\power.lua"]:48: in function <...\ElvUI_BenikUI\modules\unitframes\elements\power.lua:46>
[string "=[C]"]: in function `func'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:841: in function `UpdateChild'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:863: in function `Update'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:811: in function `Update'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1026: in function `CreateAndUpdateHeaderGroup'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1091: in function `LoadUnits'
[string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1589: in function `func'
[string "@ElvUI\Libraries\Core\oUF\factory.lua"]:20: in function <ElvUI\Libraries\Core\oUF\factory.lua:16>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 Update_AssistHeader = <function> defined @ElvUI\Core\Modules\UnitFrames\Groups\Assist.lua:42
 AuraWatch_AddSpell = <function> defined @ElvUI\Mainline\Filters\Filters.lua:1478
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 RaidRoleUpdate = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\RaidRoleIcons.lua:52
 SetSmartPosition = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Auras.lua:292
 Construct_PowerBar = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Power.lua:14
 arena1 = ElvUF_Arena1 {
 }
 RegisterForClicks = <function> defined @ElvUI\Core\Modules\UnitFrames\UnitFrames.lua:1533
 Configure_AllAuras = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Auras.lua:276
 Construct_Buffs = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Auras.lua:56
 Construct_PowerPrediction = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\PowerPrediction.lua:34
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 UpdateNameSettings = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Name.lua:14
 ADDON_LOADED = <function> defined @ElvUI\Core\Modules\UnitFrames\UnitFrames.lua:1322
 FrameGlow_CheckMouseover = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\FrameGlow.lua:299
 Configure_PVPText = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\PVPText.lua:8
 MatchGrowthX = <table> {
 }
 db = <table> {
 }
 Update_TankFrames = <function> defined @ElvUI\Core\Modules\UnitFrames\Groups\Tank.lua:72
 CreateRaisedText = <function> defined @ElvUI\Core\Modules\UnitFrames\UnitFrames.lua:251
 SetTexture_HealComm = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\HealPrediction.lua:19
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 SetStatusBarBackdropPoints = <function> defined @ElvUI\Core\Modules\UnitFrames\UnitFrames.lua:1432
 GetTalentTicks = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\CastBar.lua:360
 ClassPower_SetBarColor = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\ClassBars.lua:50
 BuffIndicator_PostUpdateIcon = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\BuffIndicator.lua:70
 FrameGlow_SetGlowColor = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\FrameGlow.lua:177
 Construct_BossFrames = <function> defined @ElvUI\Core\Modules\UnitFrames\Groups\Boss.lua:12
 GetAuraRow = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Auras.lua:92
 Construct_RaidDebuffs = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\RaidDebuffs.lua:8
 PostUpdate_PhaseIcon = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\PhaseIndicator.lua:4
 AuraUnchanged = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\Auras.lua:561
 Construct_RaidpetFrames = <function> defined @ElvUI\Core\Modules\UnitFrames\Groups\RaidPets.lua:5
 groupPrototype = <table> {
 }
 Construct_InfoPanel = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\InfoPanel.lua:6
 Configure_HealthBar = <function> defined =[C]:-1
 PostUpdateBar_AuraBars = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\AuraBars.lua:192
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 PostColorAdditionalPower = <function> defined @ElvUI\Core\Modules\UnitFrames\Elements\ClassBars.lua:494
 classMaxResourceBar = <table> {
 }
 name = "ElvUI_UnitFrames"
 SetAlpha_HealComm = <function> defined @ElvUI\Core\Modu

**Comment by Benik** [comment]
Use v4.19. ElvUI has done some changes on the raid frames

**Comment by uaeuaeuae** [comment]
thank you .
