### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by silentsnails** [Benik/BenikUI#13]
Message: ...dOns\ElvUI_BenikUI\modules\unitframes\unitframes.lua:47: attempt to call method 'CreateSoftShadow' (a nil value)
Time: Sun Oct  2 20:23:38 2022
Count: 1
Stack: ...dOns\ElvUI_BenikUI\modules\unitframes\unitframes.lua:47: attempt to call method 'CreateSoftShadow' (a nil value)
[string "=[C]"]: in function `CreateSoftShadow'
[string "@Interface\AddOns\ElvUI_BenikUI\modules\unitframes\unitframes.lua"]:47: in function `UnitShadows'
[string "@Interface\AddOns\ElvUI_BenikUI\modules\unitframes\unitframes.lua"]:200: in function <...dOns\ElvUI_BenikUI\modules\unitframes\unitframes.lua:180>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadUnits'
[string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1583: in function `func'
[string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\factory.lua"]:20: in function <...nterface\AddOns\ElvUI\Libraries\Core\oUF\factory.lua:16>
[string "=(tail call)"]: ?

Locals:

**Comment by Benik** [comment]
Fixed in v2.01. Thanks :)
