### ISSUE TITLE
Tokens @ Wotlk

### ISSUE THREAD

**Issue by FailZorD** [Benik/BenikUI#14]
Hello, 
I was wondering if the feature to track Tokens can be added on Wotlk version as it is missing as an option at Elvui->Benikui->Dashboards-> ...
Thank you in advance.

**Comment by Benik** [comment]
Γειά σου Αλέξη :)
It's in my todo list. Hopefully will be added during this week.

Cheers,
Ναι Έλληνας :)

**Comment by FailZorD** [comment]
Γειά σου φίλε,
Thanks for the fast reply and great news. Can't wait to use it!
Καλή συνέχεια.

**Comment by Benik** [comment]
All good, added at the dev version :P
