### ISSUE TITLE
Mail Icon

### ISSUE THREAD

**Issue by Keesoten** [Benik/BenikUI#16]
Mail icon appears on the minimap despite it is disabled in Datatext section. BenikUI version 4.20, ElvUI version 12.95 (retail)
![img1](https://user-images.githubusercontent.com/116836828/198365250-a16296b7-45c8-4604-af6c-b1f469216cf4.JPG)
![img2](https://user-images.githubusercontent.com/116836828/198365256-44eb3583-397a-4eb8-8fd5-0f1e46d1a038.JPG)

**Comment by thurin** [comment]
72eeafbb fixes this.  Thanks for the report.
