### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by Madsfriisi** [Benik/BenikUI#17]
9x Interface/AddOns/ElvUI_BenikUI/modules/chat/chat.lua:21: attempt to index field 'chat' (a nil value)
[string "@Interface/AddOns/ElvUI_BenikUI/modules/chat/chat.lua"]:21: in function <Interface/AddOns/ElvUI_BenikUI/modules/chat/chat.lua:19>
[string "=[C]"]: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:239: in function `SaveCacheOnCVar'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:339: in function `SaveData'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:895: in function `eventCallbackFunc'
[string "@Interface/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua"]:904: in function <...face/AddOns/Details/Libs/LibOpenRaid/LibOpenRaid.lua:902>

Locals:
self = <table> {
 OnHyperlinkLeave = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1546
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceTimer-3.0/AceTimer-3.0.lua:147
 UpdateEditboxFont = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:753
 SecureHook = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:335
 TabOnLeave = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1043
 BNGetFriendInfo = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:213
 IsUndocked = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1270
 ChatEdit_PleaseRetaint = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:687
 SocialQueueIsLeader = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:2766
 ToggleChatButton = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1251
 ScrollToBottom = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1405
 OnHyperlinkEnter = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1535
 CHAT_MSG_YELL = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:2442
 AddPluginMessageFilter = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1649
 IsEnabled = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:447
 HandleShortChannels = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1584
 BNGetGameAccountInfo = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:226
 StyleOverflowButton = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:2322
 HookSecured = true
 CreateChatVoicePanel = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:3107
 CheckLFGRoles = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:2742
 RegisterMessage = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 CopyButtonOnEnter = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:594
 GuidCache = <table> {
 }
 UpdateChatTabs = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1245
 db = <table> {
 }
 ChatFrame_ReplaceIconAndGroupExpressions = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1685
 ChatEdit_DeactivateChat = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1116
 SetEnabledState = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceHook-3.0/AceHook-3.0.lua:273
 PostChatClose = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:2607
 SnappingChanged = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1294
 GetPluginIcon = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1640
 ResetVoicePanelAlpha = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:3101
 VoiceOverlay = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:3380
 ThrottleSound = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:2450
 NewModule = <function> defined @Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:231
 ClearSnapping = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1287
 ChatEdit_PleaseUntaint = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:694
 GetLines = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:975
 Initialized = true
 FindURL = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1420
 BuildCopyChatFrame = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:3185
 GetPl

**Comment by Benik** [comment]
Should be fixed with v4.21. Thanks :)
