### ISSUE TITLE
ilevel not showing on character screen

### ISSUE THREAD

**Issue by Somora** [Benik/BenikUI#21]
**Describe the bug and post the error message, if there is one**
ilevel not showing on character screen. Option is turned on.

**Screenshots**
![image](https://user-images.githubusercontent.com/917426/202563775-36d11a5f-b197-4c1f-94d0-3854f8db7dc5.png)

**Please include the addon and game versions:**
 - BenikUI: v4.25
 - ElvUI: v13.02
 - WoW game variation (retail, WotLK, Classic Era): Retail

Thanks :)

**Comment by Benik** [comment]
It's been reported at BenikUI Discord and has been fixed at the dev branch with this commit https://github.com/Benik/BenikUI/commit/46a6cb1fb624a0f81b6437274bde5bcff16dbee1

Ti will be part of the next version. In case you want to check it out: https://github.com/Benik/BenikUI/archive/refs/heads/development.zip

Cheers :)

**Comment by Somora** [comment]
Oops sorry had to do better research first :p
Tried the development branch and it works again :)

Thank you very much for the nice UI and hard work!
