### ISSUE TITLE
Error by clicking the Widget Bars Option in ElvUI

### ISSUE THREAD

**Issue by DeaTHCorE001** [Benik/BenikUI#23]
If i open the ElvUI options and i click to BenikUI - Widget Bars the follow error is present:

1x bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))
[string "=[C]"]: ?
[string "=[C]"]: in function `SetVertexColor'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua"]:120: in function `SetColor'
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1476: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1144>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1171: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1144>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1171: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1144>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1745: in function `FeedGroup'
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1670: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1654>
[string "=[C]"]: ?
[string "@TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <TomTom/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@TomTom/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@TomTom/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:508: in function `SetSelected'
[string "@TomTom/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:185: in function <...ibs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:181>****

This is from the Checkbox Option "Color by Tier", if i click on this Checkbox, the error is displayed ...

i use wow retail 10.0.2 with dragonflay addon

**Comment by Benik** [comment]
Fixed on dev and will be part of the next version.

Cheers :)
