### ISSUE TITLE
Aura Bars Alignment

### ISSUE THREAD

**Issue by Texxer** [Benik/BenikUI#28]
**Describe the bug and post the error message, if there is one**
Aura Bars are not aligning with the corner of the frame, they are off by a few pixels to the left. It happens to the player and the target frame.

**To Reproduce**
Enable Aura Bars, Attach To Frame, Set Anchor Point Above

**Expected behavior**
Aura Bars should have the same X-axis values as the frames.

**Screenshots**
![208970712-0c34e922-8b9d-4151-8036-a2fe3062343e](https://user-images.githubusercontent.com/22458550/209358180-bfd0784d-c879-4626-bf60-8f30fec2ca70.png)

**Please include the addon and game versions:**
 - BenikUI: 4.28
 - ElvUI: 13.15
 - WoW game variation (retail, WotLK, Classic Era): Retail

**Additional context**
n/a

**Comment by Benik** [comment]
Yes, they are getting moved a bit so the shadows don't overlap. It may be fixable but I would suggest detatching the Aurabars from the frame and move it as needed.

**Comment by Texxer** [comment]
Sorry, I don't understand how the shadows would overlap. With ElvUI the Aura Bars are perfectly aligned, only BenikUI moves them to the left.

**Comment by Benik** [comment]
The shadows need some spacing between the icon and the bar. As I said above it may be fixable so it won't gets moved to the left. The solutions, till I can manage to fix it, are either disable Shadows from BenikUI options or detatch the Aurabars from the frame, so you can move them a bit to the right.

**Comment by Benik** [comment]
When I have the time... :P
