### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Imna1975** [Benik/BenikUI#29]
1x ...e\AddOns\ElvUI_BenikUI\modules\styles\addonskins-4.62.lua:336: hooksecurefunc(): AcceptFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\ElvUI_BenikUI\modules\styles\addonskins-4.62.lua"]:336: in main chunk

Locals:

**Please include the addon and game versions:**
 - BenikUI: [v2.06-AiO]
 - ElvUI: 13.15
 - WoW game variation (retail, WotLK, Classic Era): WotLK

**Additional context**

**Comment by Benik** [comment]
Should be fixed in v2.07. Thank you :)
