### ISSUE TITLE
Error with elvui 13.17 and benikui 4.29 when all dashboards are disabled

### ISSUE THREAD

**Issue by vaardu** [Benik/BenikUI#30]
**Describe the bug and post the error message, if there is one**

Message: ...ddOns/ElvUI_BenikUI/modules/dashboard/dashboards.lua:122: attempt to index field '?' (a nil value)
Time: Tue Jan  3 19:27:43 2023
Count: 1
Stack: ...ddOns/ElvUI_BenikUI/modules/dashboard/dashboards.lua:122: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_BenikUI/modules/dashboard/dashboards.lua"]:122: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**To Reproduce**
Simply disable all dashboards from BenikUI settings and this will pop up with every area load and relog/reload.

**Please include the addon and game versions:**
 - BenikUI: 4.29
 - ElvUI: 13.17
 - WoW game variation (retail, WotLK, Classic Era): Retail

**Comment by Benik** [comment]
Should be fixed in v4.30. Thank you :)

**Comment by vaardu** [comment]
Thank you for the continued effort
