### ISSUE TITLE
Middle datatext panel is missing

### ISSUE THREAD

**Issue by Keesoten** [Benik/BenikUI#32]
The middle panel is missing despite being enabled in settings. It happened after updating ElvUI to the 13.25 version.
![изображение](https://user-images.githubusercontent.com/116836828/217791112-d99ed56e-07c3-4c48-a889-c96054d2792b.png)

**Comment by Benik** [comment]
You also updated BenikUI to v4.33?

**Comment by Keesoten** [comment]
Yes, and the panel is still missing even after update

**Comment by Benik** [comment]
go to BenikUI options -> Datatexts, you will find a Reset button for the Middle Datatext. See if that works for you

**Comment by Keesoten** [comment]
Didn't help. I even tried to reinstall both addons and removed WTF folder in case something was messed up there but the panel didn't appear anyway.

**Comment by Benik** [comment]
try after typing in chat `/buierror on`

**Comment by Benik** [comment]
This is a known ElvUI issue, that has been fixed in ElvUI dev version and will be part of the next release

**Comment by Keesoten** [comment]
oh, ok! thank you for your help!
