### ISSUE TITLE
Benik UI not showing up in ElvUI setting/options menu after patch

### ISSUE THREAD

**Issue by bigredgod** [Benik/BenikUI#36]
After the recent dragonflight patch and updating the BenikUI in curse forge i do not see the Benik UI options in the ElvUI settings. i cannot reinstall my profile to be what it was previous to patch. after restart Benik UI gives message that it is a loaded addon
**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. be able to reinstall Benik UI and reconfigure my UI

**Screenshots**
![WoWScrnShot_050323_105834](https://user-images.githubusercontent.com/132485930/235987150-73d53da3-ae8f-438a-9613-57bf669b2d85.jpg)

**Please include the addon and game versions:**
 - BenikUI: 4 .36
 - ElvUI: 13.29
 - WoW game variation (retail, WotLK, Classic Era): RETAIL

**Additional context**

**Comment by Benik** [comment]
Please update ElvUI to v13.30+
