### ISSUE TITLE
878x ElvUI_BenikUI/modules/shadows/addonskins.lua

### ISSUE THREAD

**Issue by Mothamoz** [Benik/BenikUI#40]
878x ElvUI_BenikUI/modules/shadows/addonskins.lua:70: attempt to index field 'Backdrop' (a nil value)
[string "@ElvUI_BenikUI/modules/shadows/addonskins.lua"]:70: in function <ElvUI_BenikUI/modules/shadows/addonskins.lua:29>
[string "=[C]"]: in function `ApplyStyle'
[string "@ElvUI_BenikUI/modules/shadows/addonskins.lua"]:78: in function <ElvUI_BenikUI/modules/shadows/addonskins.lua:18>
[string "=[C]"]: in function `CreateBar'
[string "@DBM-Core/DBM-Core.lua"]:10057: in function `Start'
[string "@DBM-Party-WoD/SMBurialGrounds/SMBGTrash.lua"]:82: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:975: in function <DBM-Core/DBM-Core.lua:962>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:975: in function <DBM-Core/DBM-Core.lua:962>

Locals:
frame = DBT_Bar_1 {
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 shadow = Frame {
 }
 BottomRightCorner = Texture {
 }
 iborder = Frame {
 }
 PixelSnapDisabled = true
 Center = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 BottomEdge = Texture {
 }
 backdropInfo = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 oborder = Frame {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 template = "Transparent"
 obj = <table> {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 0 = <userdata>
}
tbar = DBT_Bar_1Bar {
 0 = <userdata>
 PixelSnapDisabled = true
}
icon1 = DBT_Bar_1BarIcon1 {
 PixelSnapDisabled = true
 backdrop = Frame {
 }
 0 = <userdata>
}
icon2 = DBT_Bar_1BarIcon2 {
 PixelSnapDisabled = true
 backdrop = Frame {
 }
 0 = <userdata>
}
name = DBT_Bar_1BarName {
 0 = <userdata>
}
timer = DBT_Bar_1BarTimer {
 0 = <userdata>
}
iconSize = 30
(*temporary) = nil
(*temporary) = nil
(*temporary) = "BOTTOMRIGHT"
(*temporary) = DBT_Bar_1 {
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 shadow = Frame {
 }
 BottomRightCorner = Texture {
 }
 iborder = Frame {
 }
 PixelSnapDisabled = true
 Center = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 BottomEdge = Texture {
 }
 backdropInfo = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 oborder = Frame {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 template = "Transparent"
 obj = <table> {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 0 = <userdata>
}
(*temporary) = "TOPRIGHT"
(*temporary) = -1
(*temporary) = 1
(*temporary) = <userdata>
(*temporary) = "attempt to index field 'Backdrop' (a nil value)"
bar = <table> {
 totalTime = 10.900000
 lastUpdate = 1248.193000
 Update = <function> defined =[C]:-1
 id = "Timer164907cd	Creature-0-4238-1176-7363-75715-00055A04F8"
 owner = <table> {
 }
 countdownMax = 4
 countdown = 0
 colorType = 5
 ApplyStyle = <function> defined =[C]:

**Comment by Benik** [comment]
It's fixed on dev version. I will release a new version tonight. Thank you 😊
