### ISSUE TITLE
Flightmode and AddonSkins

### ISSUE THREAD

**Issue by Imiona** [Benik/BenikUI#44]
Hey

When using AddonSkins with Flight Mode enabled, after landing, the whole Chat disappears. Only /rl fixes this.

ELV 13.35
Skins 4.68
Benik 4.38

Can you reproduce this?

Danke

**Comment by Imiona** [comment]
Retail, but how is this possible?

I reinstalled addonskins and deleted all saved variables, but it still doesnt work, chat disappears when landing.

![Wow 2023-07-02 15-23-48](https://github.com/Benik/BenikUI/assets/11210717/7d020261-020f-49b0-a060-a6a2ad6c7aef)

**Comment by Benik** [comment]
Should be fixed on the latest dev version. Thanks for the report :)

**Comment by Imiona** [comment]
Fixed, thx Benik ;)
