### ISSUE TITLE
Doesn´t show but it´s loaded

### ISSUE THREAD

**Issue by Kevko92** [Benik/BenikUI#45]
**Describe the bug and post the error message, if there is one**
.eElvUI_BenikUI/modules/shadows/WeakAuras.lua:81: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@ElvUI_BenikUI/modules/shadows/WeakAuras.lua"]:81: in function <...eElvUI_BenikUI/modules/shadows/WeakAuras.lua:70>
[string "@ElvUI_BenikUI/modules/shadows/WeakAuras.lua"]:89: in function `WeakAuras'
[string "@ElvUI_BenikUI/modules/shadows/shadows.lua"]:296: in function `Initialize'
[string "@ElvUI_BenikUI/init.lua"]:54: in function `InitializeModules'
[string "@ElvUI_BenikUI/init.lua"]:80: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-42/LibElvUIPlugin-1.0.lua"]:303: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:276: in function <ElvUI/Core/init.lua:275>
[string "=[C]"]: ?
...
[string "@FrameXML/UIParent.lua"]:547: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:752: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**To Reproduce**
Just logging in, but only on my DH when i log in my shamy everything was fine no bugs and everything was there.
**Expected behavior**

**Screenshots**

**Please include the addon and game versions:**
 - BenikUI: 4.40
 - ElvUI: 13.42
 - WoW game variation (retail, WotLK, Classic Era): retail

**Additional context**

**Comment by Benik** [comment]
Should be fixed in v4.41
