### ISSUE TITLE
Issue with BenikUI & Leatrix Maps

### ISSUE THREAD

**Issue by millsmason91** [Benik/BenikUI#47]
**To Reproduce**
Steps to reproduce the behavior: Use Leatrix with Benik.

**Please include the addon and game versions:**
 - BenikUI: 2.16
 - ElvUI: 13.52
 - WoW game variation (retail, WotLK, Classic Era): Classic

**Additional context**
Leatrix causes Map Breakage with BenikUI

PREVIEW: https://ibb.co/6mLDNHf
![Uploading WoWScrnShot_112023_205607.jpg…]()

**Comment by millsmason91** [comment]
I love BenikUI, it's honestly the best, but leatrix maps and letrix plus seem to break the BenikUI Map.

Even when elvui map is disabled.

**Comment by Texxer** [comment]
It doesn't happen on Retail, just fyi.

**Comment by millsmason91** [comment]
I'm only experiencing the issue in Classic.
