### ISSUE TITLE
Shadow & Light Skin Fix

### ISSUE THREAD

**Issue by Shadowinplay** [Benik/BenikUI#51]
Hey Benik, could you fix this minor bug with the Shadow & Light skin?

Apparently the skin for the location panel coordinates is on another frame level than its parent frame, so it's causing some overlapping with other frames, such as the buffs frame from ElvUI as show on the screenshot below. The frame level of the BUI skin is set to level 5 and the coords frame is level 3. The frames in question are SLE_LocationPanel_X and SLE_LocationPanel_Y.

![WoWScrnShot_062624_174239](https://github.com/Benik/BenikUI/assets/111493171/f5f929ca-ff57-4a1d-b9bb-d18903d5121a)

Also, another suggestion is to change the (y) position of the dropdown menu from the location panel to -6 (doesn't overlap if BUI shadows are enabled) to avoid overlapping with the main panel. The frames are SLE_LocationPanel_RightClickMenu1 and SLE_LocationPanel_RightClickMenu2.

Before (unedited with BUI shadows disabled):
![WoWScrnShot_062624_172642](https://github.com/Benik/BenikUI/assets/111493171/1180e6b7-2180-477e-bf21-f3a60f6bfc7d)

After (edited with BUI shadows enabled):
![WoWScrnShot_062624_173521](https://github.com/Benik/BenikUI/assets/111493171/04b709a1-e507-4488-91e5-0c2b77ac8ac0)

**Comment by Benik** [comment]
Should be fixed on dev version. Thanks :)
