### ISSUE TITLE
Reputation LUA Error. Kills some UI

### ISSUE THREAD

**Issue by FailZorD** [Benik/BenikUI#56]
Loading the UI after an update from LocationPlus for the Beta this new error popped up:

> Message: ...dOns/ElvUI_BenikUI/modules/dashboard/reputations.lua:293: attempt to index local 'info' (a nil value)
> Time: Wed Aug 21 20:00:56 2024
> Count: 1
> Stack: ...dOns/ElvUI_BenikUI/modules/dashboard/reputations.lua:293: attempt to index local 'info' (a nil value)
> [string "@Interface/AddOns/ElvUI_BenikUI/modules/dashboard/reputations.lua"]:293: in function `PopulateFactionData'
> [string "@Interface/AddOns/ElvUI_BenikUI/modules/dashboard/reputations.lua"]:377: in function `ToggleReputations'
> [string "@Interface/AddOns/ElvUI_BenikUI/modules/dashboard/reputations.lua"]:401: in function `CreateReputationsDashboard'
> [string "@Interface/AddOns/ElvUI_BenikUI/modules/dashboard/reputations.lua"]:405: in function `LoadReputations'
> [string "@Interface/AddOns/ElvUI_BenikUI/modules/dashboard/dashboards.lua"]:308: in function `Initialize'
> [string "@Interface/AddOns/ElvUI_BenikUI/init.lua"]:56: in function `InitializeModules'
> [string "@Interface/AddOns/ElvUI_BenikUI/init.lua"]:82: in function `?'
> [string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
> [string "=[C]"]: in function `Initialize'
> [string "@Interface/AddOns/ElvUI/Core/init.lua"]:302: in function <Interface/AddOns/ElvUI/Core/init.lua:301>
> [string "=[C]"]: ?
> [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
> ...
> [string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
> [string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
> [string "=[C]"]: in function `CreateFrame'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>
> 
> Locals: self = <table> {
>  modules = <table> {
>  }
>  defaultModuleState = true
>  ItemsList = <table> {
>  }
>  hooks = <table> {
>  }
>  enabledState = true
>  ProfessionsDB = <table> {
>  }
>  TokensDB = <table> {
>  }
>  defaultModuleLibraries = <table> {
>  }
>  baseName = "ElvUI_BenikUI"
>  ItemsDB = <table> {
>  }
>  name = "ElvUI_BenikUI_Dashboards"
>  SystemDB = <table> {
>  }
>  orderedModules = <table> {
>  }
>  ReputationsList = <table> {
>  }
>  CurrencyList = <table> {
>  }
>  FactionsDB = <table> {
>  }
>  moduleName = "Dashboards"
> }
> Collapsed = <table> {
> }
> numFactions = 115
> factionIndex = 6
> headerIndex = 5
> info = nil
> (*temporary) = nil
> (*temporary) = 6
> (*temporary) = nil
> (*temporary) = "Council of Dornogal"
> (*temporary) = 2590
> (*temporary) = 5
> (*temporary) = true
> (*temporary) = nil
> (*temporary) = false
> (*temporary) = "attempt to index local 'info' (a nil value)"
> mod = <table> {
>  modules = <table> {
>  }
>  defaultModuleState = true
>  ItemsList = <table> {
>  }
>  hooks = <table> {
>  }
>  enabledState = true
>  ProfessionsDB = <table> {
>  }
>  TokensDB = <table> {
>  }
>  defaultModuleLibraries = <table> {
>  }
>  baseName = "ElvUI_BenikUI"
>  ItemsDB = <table> {
>  }
>  name = "ElvUI_BenikUI_Dashboards"
>  SystemDB = <table> {
>  }
>  orderedModules = <table> {
>  }
>  ReputationsList = <table> {
>  }
>  ...

**To Reproduce**
Loading any time pops this message.

**Expected behavior**
To not appear as an error and should work when selecting Reputation as Exp Bar.

**Screenshots**
No need pure LUA error there.

**Please include the addon and game versions:**
 - BenikUI: Current Dev as 21/08/2024 (4.52)
 - ElvUI: Live Version: v13.74
 - WoW game variation (retail, WotLK, Classic Era): Beta (TWW)

**Comment by Skuriles** [comment]
Some problem here. 
It always let's the whole quest tracker vanish

**Comment by hsramm** [comment]
Same.

**Comment by Benik** [comment]
It's a Blizz issue that breaks Reputation at the Character frame. A reload doesn't fix the issue.
Solutions:
- **Relog** your char or
- Disable Reputation Dashboard via BenikUI options or
- Use the dev version that has the Reputation Dashboard disabled, till Blizz fixes the issue. https://github.com/Benik/BenikUI/archive/refs/heads/development.zip
