### ISSUE TITLE
Reputation is greyed out under Dashboards

### ISSUE THREAD

**Issue by uhbeta** [Benik/BenikUI#59]
I'm unable to access the reputation dashboard in Benikui.  I can access and display content from the others (General/tokens/professions/items).

I have tried changing which reputation should be tracked and this does not change anything.
I have previously been able to track all of my reputations this expansion (except Bran he was always bugged at 1/1).

![image](https://github.com/user-attachments/assets/201227d7-25fd-4e29-bf35-efb27f2461ab)

 - BenikUI: 4.54
 - ElvUI: 13..77
 - WoW game variation (retail, WotLK, Classic Era): Retail

**Comment by Benik** [comment]
It's been disabled till Blizzard fixes the messy Character Reputation frame

**Comment by uhbeta** [comment]
Thank you for the crazy fast response.

**Comment by uhbeta** [comment]
Thank you for the crazy fast response.
