### ISSUE TITLE
EquipmentSets onClick not show all list of available sets

### ISSUE THREAD

**Issue by rezequielp** [Benik/BenikUI#61]
I created 2 equipment sets and added text data in BenikUI middle panel so i can click it and pick the set that i want. But just show me one set in list options. In mouseover show all sets created.

**To Reproduce**
Create 2 equipment set
Add equipment set to BenikUI middle panel
Click on in to see sets available

**Expected behavior**
On click, all set available have to be listed to select

**Screenshots**
![Screenshot_5](https://github.com/user-attachments/assets/c81eddd5-5a31-4440-ba61-23abffef5cfb)

**Please include the addon and game versions:**
 - BenikUI: 2.25
 - ElvUI: 13.81
 - WoW game variation (retail, WotLK, Classic Era): Cataclysm Classic

**Additional context**
I see commits in ElvUI recently
https://github.com/tukui-org/ElvUI/commits/979bcf134fdfd8150bb4f9cec190f71f6d409f8e/ElvUI/Core/Modules/DataTexts/EquipmentSets.lua

**Comment by Repooc** [comment]
this doesnt have anything to do with benikui, its elvui datatext itself which will be fixed in 13.82
