### ISSUE TITLE
Siren Isle Items - Not Managed

### ISSUE THREAD

**Issue by thetravellor** [Benik/BenikUI#63]
**Describe the bug and post the error message, if there is one**
In ElvUI / BenekUI, the new Siren Isle bufss are not being managed and cannot be managed by either elvui or benekui, overwrite actiobars

**To Reproduce**

Install Elvui, Benekui, install as Caster DPS, select V3 action bars and unit frames

**Expected behavior**
The item is managed 

**Screenshots**

![image](https://github.com/user-attachments/assets/cd014ac4-4ade-4935-860d-92fa126e4ce2)

**Please include the addon and game versions:**
 - BenikUI: 1.15.5
 - ElvUI: 13.81
 - WoW game variation (retail, WotLK, Classic Era): 11.0.7

**Additional context**

**Comment by E-Tsx** [comment]
that icon you see there over the actionbars is not from elvui or benikui, thats from Kaliel's tracker, you need to adjust/move it in that addon
