### ISSUE TITLE
Details Addon Skin

### ISSUE THREAD

**Issue by Avabehe** [Benik/BenikUI#8]
If I use the AddonSkin for Details, the overall Damage doesnt work anymore, is this a problem from BenikUI or from Details itself?

**Comment by Repooc** [comment]
> If I use the AddonSkin for Details, the overall Damage doesnt work anymore, is this a problem from BenikUI or from Details itself?

benikui, addonskins do not change how details works, benikui just provides his profile for details... you will need to talk to them if the addon isnt tracking stuff correctly

**Comment by Avabehe** [comment]
But its only if I use the BenikUI Profile, if I use the StandardProfiles it works.
I think they have changed anything in the Profilesyntax. If I compare the Lines of the Standard-Profile and the Benikui Profile, I see that the Standardprofile has mich more lines

**Comment by Avabehe** [comment]
Update:
Its only in the open world, in dungeons or raids the overall damage works without problem with BenikUI Style
