### ISSUE TITLE
Benkui Style disapear on action bars

### ISSUE THREAD

**Issue by haazill** [Benik/BenikUI#9]
Hi,
First of all, thanks for putting some style in the fight, always important ;)

I have a problem, I use Elvui, Benkui and Merathilis and I never had any bugs....

Since the last update, the "Benkui Style" doesn't appear anymore, only on the action bars and having tested with the other addons, one by one, it turns out that this is fixed if I deactivate Merathilis.

Maybe it's a nuisance, but this is just to point it out and hopefully fix it :)

Thanks a lot and long time ;)

**Comment by Merathilis** [comment]
Hi @haazill it is mainly my fault that i hide the BenikUI. I just commited i fix for the issue, go and download my dev version if you cant wait.

**Comment by haazill** [comment]
Serious so fast thanks a lot MR !!

**Comment by haazill** [comment]
It's perfect ;) Thanks a lot and hope you have help like you help all.

phil
